### ISSUE TITLE
error in opening the count.webm or count.mp4

### ISSUE THREAD

**Issue by pplaodong** [GenericMappingTools/gmt-for-geodesy#11]
Dear community,

I met a problem in opening the count.webm and count.mp4. Error messages as follows:

xdg-open: no method available for opening 'count.mp4'

/usr/bin/xdg-open: line 658: 28681 Bus error               (core dumped) $browser "$1" > /dev/null 2> /dev/null
xdg-open: no method available for opening 'count.webm'

I am using CentOS Linux release 7.3.1611. I am wondering how to solve the problem.

Best,
Pingping Huang (gmt-for-geodesy learner)

**Comment by PaulWessel** [comment]
Googling indicates that the standard video viewer for CentOS is VLC.  Do you have it installed? I believe xdg-open will call the default vide viewer for MP4 files but if you do not have a viewer then this error is likely the result.

**Comment by seisman** [comment]
For WebM files, you should be able open and view them directly in your web browser (e.g., Firefox).

**Comment by pplaodong** [comment]
Thanks. Problem solved.
