### ISSUE TITLE
How to update to gmt 6.4 on MacOS

### ISSUE THREAD

**Issue by Elise-J10** [GenericMappingTools/gmt-for-geodesy#14]
I am borrowing a Mac13 and it currently has gmt version 6.3.0. I need version 6.4.0 but am having trouble updating it. I use XQuartz. I have tried typing "brew upgrade gmt" and "sudo brew upgrade gmt" but this is not working. I get these errors. How can I fix this and upgrade? 

<img width="547" alt="Screen Shot 2022-07-01 at 7 12 09 AM" src="https://user-images.githubusercontent.com/108543071/176940199-4c6e4a0a-c910-4229-90e5-0b3bf860b410.png">
<img width="547" alt="Screen Shot 2022-07-01 at 7 11 47 AM" src="https://user-images.githubusercontent.com/108543071/176940201-d8292edf-ebb3-4575-b8d5-304e238d306c.png">

**Comment by joa-quim** [comment]
What the errors are saying is that you should not run *homebrew* as root. *i.e.* do not run the command under `sudo ...``

**Comment by Elise-J10** [comment]
I have also tried without sudo. That is what gave me the very long results beginning with "/usr/local/Homebrew is not writable

**Comment by joa-quim** [comment]
Ah, the Unix beauties. What about installing a Boot Camp  Windows on your Mac to have a troubless OS?

Ok, joke aside (is it :) ?), perhaps the better is to install the GMT bundle. Pick the appropriate .dmg (the x86_64 if it's not an M1 Mac) from
https://github.com/GenericMappingTools/gmt/releases/tag/6.4.0

**Comment by Elise-J10** [comment]
Okay, I will try downloading the .dmg. How do I install it? (I am verrryy new to coding. I don't know how to command an install)

**Comment by PaulWessel** [comment]
Double-clicking on the installer icon is not exactly coding - it is just installing software like anything else on a Mac.
