### ISSUE TITLE
Fix Max Jones links? 

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt-for-geodesy#15]
@maxrjones, we should changes the links to https://github.com/meghanrjones in the readme files, right?

**Comment by Esteban82** [comment]
I found two links:

https://github.com/GenericMappingTools/gmt-for-geodesy/blob/main/README.md
https://github.com/GenericMappingTools/gmt-for-geodesy/blob/main/2_basics/README.md

**Comment by maxrjones** [comment]
Thanks @Esteban82, fixed in https://github.com/GenericMappingTools/gmt-for-geodesy/commit/6018e01826e4de18d5480a84584c28939407c10a and https://github.com/GenericMappingTools/gmt-for-geodesy/commit/5203805e42cceab979bbe906f9256552ad0ab5b4
