### ISSUE TITLE
Who is doing what in 2022?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt-for-geodesy#2]
Hi instructors, I will be sending out preliminary schedules by this weekend for the UNAVCO/GMT course.  However, faulty memory means I am not sure who said they would do what.  I am most sure about Eric Xu doing geodesy and @seisman doing Seismology, but not entirely sure of who else have picked something they want to present on.  We have the sections on points and lines that @joa-quim have done and Grids and Images that Leo used to do (but he is not available this summer).  I am unsure what @meghanrjones and @Esteban82 said in our February community meeting... I am available to do whatever is left over as backup.

Please let me know as soon as possible if you have firmer memories and state what you expect to do.  As it seems, we will again do live presentations, with at least the exception of Eric.

**Comment by Esteban82** [comment]
Hi Paul! I don't remember well but I think I haven't proposed for anything in particular. I think you just make a general comment and ask that the rest send you an email. What are the issues left to cover? Bash, basics, grids and animations? 
Remember that, if possible, I would like to make a breakout group in spanish.

**Comment by Esteban82** [comment]
BTW, Do we still need more instructors to help with the classes? How many students are enrolled?

**Comment by PaulWessel** [comment]
There will be 66 students with access to Slack and another 60 or so watching on YouTube live.  Similar to last year I think.

**Comment by PaulWessel** [comment]
> Remember that, if possible, I would like to make a breakout group in spanish.

Yes, will do.

**Comment by meghanrjones** [comment]
I'll take basics unless someone else really wants that component.

**Comment by PaulWessel** [comment]
Notes from last year says

1. Layout, objectives, organization of workshop [how we will run this workshop] PAUL
2. GMT basics, command line, UNIX skills MEGHAN
3. Plot points, lines, polygons, text JOAQUIM
4. Plot grids, contours, shading, remote files LEO
5. Plot focal mechanisms DONGDONG
6. Plot GPS vectors ERIC
7. Generate animations PAUL
8. Final projects PAUL/ALL

@meghanrjones, did you mean the same (which includes UNIX and bash stuff)?

**Comment by meghanrjones** [comment]
I think you went over unix/bash last year (https://www.youtube.com/watch?v=7t_fzeEMfbI&list=PLzmugeDoplFPtWkrCqWWWZGZzPQr_k0Kx&index=3) but I could bundle it with basics this year.

**Comment by PaulWessel** [comment]
Sorry, not meaning to load stuff on you - just was not sure (and did not look at video evidence).  I am happy to do the bash/UNIX stuff if need be; we can see how we shape up with the other items.

**Comment by Esteban82** [comment]
I think I could do the grids. Although I am not familiar to work with Jupyter notebooks.

**Comment by PaulWessel** [comment]
I am also not familiar with the Jupyter notebooks scheme and will try to see if I can make sense of it this weekend.  The fallback is to do the same as last year (Visual Studio Code, terminal).

**Comment by PaulWessel** [comment]
This year we will not have a separate "Installation Help" session since pretty much all were able to install last year without issues.  The handfull of people who might get stuck can get hold of us via the GitHub page.

I will lead a < 1hour introduction zoom session the week before the workshop.  Like previous years, I will hold it twice to accommodate all time zones.  Instructors are encouraged to attend the one in their time zone but you do not have to.  I am just explaining how the workshop will be run.

I have created a UNAVCO 2022 Google Docs folder where I have notes regarding the sharing of tasks and the schele, and in the slides folder you will find my presentation draft.  Happy to take comments asap on schedule and slides.  The days and times follows the when2meet responses, hence a short session followed by a longer one.  I will need Melissa to send zoom link to the two introduction sessions on Monday, probably.

https://drive.google.com/drive/folders/1rnp5dYdFEgbtHNovCLc26_pk2BGnuE9F?usp=sharing

Given my mind has been elsewhere the last months (deep in research) I do not feel particularly well prepared to switch from VSC and terminal to Jupyter which I never use.  We should decide very quickly if we are to use Meghan's suggested layout of if we just replicate the 2021 git repo for 2022 and direct students to that instead.

**Comment by PaulWessel** [comment]
As written, my introduction says we will use 6.4.  But are there things in 6.4 not in 6.3 that we will depend on? Perhaps we can be flexible and say 6.3 or later?  Perhaps auto-legend **-l** in **grdvector** _might_ be important?

**Comment by Xiaohua-Eric-Xu** [comment]
@PaulWessel , I'll experiment with that, also the new coloring option in velo. I am not very familiar with Jupyter Notebook either. Does anyone has a good jupyter example that I could start with?

**Comment by joa-quim** [comment]
I have no idea on how to set up a Jupyter notebook to work with plain GMT CLI. I guess it's possible but no idea how.

**Comment by meghanrjones** [comment]
Let's just stick with bash scripts. Do you prefer to keep creating new repositories for each year or use this repository (gmt-for-geodesy) with tags/releases marking each year's material? I would lean towards the second option since it may simplify setup.

**Comment by meghanrjones** [comment]
the schedule looks good to me

**Comment by PaulWessel** [comment]
Note that by going to three days we are giving both geodesy and seismology more time - which seems reasonable giving this is GMT for geodesy.  So @seisman and @Xiaohua-Eric-Xu will both have a bit more time (80 minutes this year vs 50? last year).

**Comment by Esteban82** [comment]
Paul, I will edit the content of 4_Grids (since it was done by Leo). I will adapt it to me. When is the deadline to do so?

**Comment by PaulWessel** [comment]
Probably a day before we start, so maybe July 5?

**Comment by Esteban82** [comment]
Ok. Thanks.

**Comment by seisman** [comment]
> As it seems, we will again do live presentations, with at least the exception of Eric.

Just want to let you know that, I probably can't do a live presentation this year, because I'm having serious network latency when I share my screen in Zoom. The sound and video are good, but the screen sharing is delayed by several seconds. I'll see if I can resolve the network issue, otherwise, I'll record a video instead.

**Comment by PaulWessel** [comment]
OK, that is fine @seisman.  I guess we will need to sort out how videos are played - I am guessing this will be done by Melissa but not sure.
