### ISSUE TITLE
How to run test 1

### ISSUE THREAD

**Issue by KamogeloBaloyi** [GenericMappingTools/gmt-for-geodesy#22]
I'm trying to run the test1 in Ubuntu 20.04

kamogelo@kamogelo:/usr/bin/gmt-for-geodesy/0_hw1$ ./test_1.sh
GPL Ghostscript 9.55.0: **** Could not open the file test1.pdf .
**** Unable to open the initial device, quitting.
psconvert [ERROR]: System call [gs -q -dNOPAUSE -dBATCH -dNOSAFER -dPDFSETTINGS=/prepress -dDownsampleColorImages=false -dDownsampleGrayImages=false -dDownsampleMonoImages=false -dUseFlateCompression=true -dEmbedAllFonts=true -dSubsetFonts=true -dMonoImageFilter=/FlateEncode -dAutoFilterGrayImages=false -dGrayImageFilter=/FlateEncode -dAutoFilterColorImages=false -dColorImageFilter=/FlateEncode -dSCANCONVERTERTYPE=2 -dALLOWPSTRANSPARENCY -dMaxBitmap=2147483647 -dUseFastColor=true -sDEVICE=pdfwrite  -g4895x5211 -r720 -sOutputFile='test1.pdf' '/home/kamogelo/.gmt/sessions/gmt_session.65478/psconvert_65482d.eps'] returned error 256.
end [ERROR]: Failed to call psconvert
end [ERROR]: gmtinit_process_figures returned error 79

**Comment by PaulWessel** [comment]
Cutting it a big close to the workshop with install issues, no?  If you have installed things in the system directory /usr/bin then you dont in general have permissions to create files.  We recommend you close the gmt-for-geodesy to one of your own directories (e.g., home directory) and run things from there.

**Comment by PaulWessel** [comment]
No worries.  And I mean "clone" not close above.

**Comment by KamogeloBaloyi** [comment]
It worked. Thank you so much. Regards
