### ISSUE TITLE
Need to add one more homework to make sure that supplemental modules are available

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt-for-geodesy#25]
One user reports that he can't use `meca` and `coupe`. 

The reason is that he builds GMT source codes and it seems the building is incomplete, so he can use core modules like `basemap` and `coast`, but can't use `meca`, `coupe` and `velo`.

**Comment by PaulWessel** [comment]
Hm, yikes.  OK, it is good to add a check that supplements are built, I agree.

**Comment by PaulWessel** [comment]
I dont know who it was and @seisman is hopefully asleep by now...
