### ISSUE TITLE
2023 GMT for Geodesy Short Course - Instructors discussion

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/gmt-for-geodesy#33]
The deadline for proposing a short course for the 2023 Technical Short Courses is February 13. I'm opening this issue for discussion about organizing and teaching the short course. 

My suggestion is to submit an application with a different proposed format than past years, more similar to the [PyGMT short course at EGU](https://github.com/GenericMappingTools/egu22pygmt), to make timing more flexible for volunteer instructors. In this case, instructors could record presentations ahead of time. We could also host a couple "office hours" where instructors are available to help students with projects. I think it would also be nice to have the wrappers featured a bit more.

@GenericMappingTools/gmt-team and @GenericMappingTools/pygmt-team - can you please share if you'd be interested in contributing to this year's should course and any comments on the proposed new structure?

The application questions have been copied to https://hackmd.io/@pygmt/Hk3DQyxas for drafting.

**Comment by Esteban82** [comment]
I am interest. 

About the structure, all the presentations would be available at the beginning, right?

**Comment by maxrjones** [comment]
> About the structure, all the presentations would be available at the beginning, right?

Yeah, the presentations would be available online (probably through YouTube) in advance of the office hours.

**Comment by joa-quim** [comment]
Yes, I'm in too. And fully agree that we should focus more in the wrappers (I've been advocating that for the last 2 editions).

In fact I actually think we should aim to a transition mode, where we show how things are done in hardcore CLI as comparing to wrappers.

It is my conviction for some years already that very few new users are willing to learn the GMT _Alphabet language_

**Comment by PaulWessel** [comment]
The only caveat is that we are setting up students for GMTSAR which is all CLI. So we have to be sensitive to what Sandwell needs us to do.

**Comment by maxrjones** [comment]
> Not sure if I could be helpful here …?

You could definitely be helpful if you're interested! You'd be welcome to join for any of the parts, including recording one of the "lectures" or helping out with the office hours.

**Comment by Xiaohua-Eric-Xu** [comment]
I am interested and happy to help!

**Comment by KristofKoch** [comment]
Ok, @maxrjones - count me in.

**Comment by maxrjones** [comment]
> I am thinking that for the office hours we could offer different languagues. It would be like last year but we could announce it in advance. I think that could encourage students that are don't speak english fluently. Each instructor should say in which languages he/she can help.
> 
> The languagues could be: english, spanish, portuguese?, norwegian?, ...

Great idea! For me, I'll need to help in english.

> The only caveat is that we are setting up students for GMTSAR which is all CLI. So we have to be sensitive to what Sandwell needs us to do.

Do you know if Dave is on GitHub? I think we can refine the topics after submission to make sure we have enough CLI covered, but we will need to know what dates they are suggesting for the GMTSAR workshop before submitting our application.

**Comment by maxrjones** [comment]
Hi @dsandwell, we're coordinating a GMT proposal for the EarthScope short courses this summer. If you're leading a GMTSAR shortcourse proposal, do you mind sharing which dates you've selected so that we can make sure the proposed GMT dates happen first?

**Comment by maxrjones** [comment]
> Hi Max, How about GMTSAR July 25-28 or August 1-4? Would that work for the GMT course earlier? Thanks, David

Great, thanks for the information!

@joa-quim @Esteban82 @KristofKoch @Xiaohua-Eric-Xu would June 26 - 29 work for you for the GMT course? This would mean releasing the video lectures the week before and hosting some office hours that week.

**Comment by PaulWessel** [comment]
I will look at my stuff as well and see what i can prerecord as well, Even if unsure about office hours

**Comment by KristofKoch** [comment]
Sorry I'm not available the whole week July 24-30 – preparing stuff is possible though.

**Comment by Xiaohua-Eric-Xu** [comment]
@maxrjones I am fine with the time.

**Comment by Esteban82** [comment]
It's ok for me.

**Comment by Esteban82** [comment]
> Sorry I'm not available the whole week July 24-30 – preparing stuff is possible though.

July or june? In July will be the gmtsar course.

**Comment by joa-quim** [comment]
That time in June is OK for me but not so much for July
.

**Comment by maxrjones** [comment]
> > Sorry I'm not available the whole week July 24-30 – preparing stuff is possible though.
> 
> July or june? In July will be the gmtsar course.

Yes, the proposed days for GMT are in June, in advance of GMTSAR. @KristofKoch do you have any availability June 26 - 29?

**Comment by maxrjones** [comment]
Thanks for all your input! I submitted an application with [answers archived on HackMD](https://hackmd.io/@pygmt/Hk3DQyxas). I'll share out when we hear back.

**Comment by maxrjones** [comment]
Melissa confirmed that we're on for the 2023 short course. The dates for four of the scheduled courses are below. Let's start planning the specific lectures and recordings next month (April). Thanks for all of your engagement on this - looking forward to working together!
May 1-4: GNSS-IR
June 26-29: GMT
July 25-28:GMTSAR
Sep 25-28: GNSS-PPP

**Comment by KristofKoch** [comment]
> Let's start planning the specific lectures and recordings next month (April).

… any updates?

**Comment by maxrjones** [comment]
Apologies for the slow reply. Here's a timeline for the remainder of the preparation tasks:
May 03 - Determine who will record which lectures
May 05 - Open applications
May 05 - Schedule office hours with instructors (I will send out a survey)
May 22 - Close application
May 26 - Finish applicant selection
May 29 - Notify participants
June 13- Upload recorded lectures to GMT google drive
June 13-20 - Process lectures and post on EarthScope website
June 20 - Share zoom and slack info with participants, offer help with installation
June 27-29 - Office hours

The proposed lectures are:
1. UNIX and bash introduction
2. GMT Basics
3. Symbols and lines
4. Grids and mages
5. Seismology
6. Geodesy
7. Animations

Optionally, we could record lectures on:
1. PyGMT
2. GMT.jl
3. GMT/MEX

Does anyone have preferences as to which lecture they would like record? The content could be adjusted from last year's material for the new format.

**Comment by Esteban82** [comment]
Great Max!

I would like to do 4. Grids and Images.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Max, I could do 6 as before.

**Comment by KristofKoch** [comment]
If you think I should give it a try I could do _3. Symbols and Lines_.

**Comment by PaulWessel** [comment]
> If you think I should give it a try I could do _3. Symbols and Lines_.

That would be great I think

**Comment by maxrjones** [comment]
Thanks everyone! Please upload videos at https://drive.google.com/drive/folders/1l_pf1sutmdcHvKl7cvbiJexX5qrniIir?usp=share_link by June 13; send me an email at maxjones@hawaii.edu if you need access. Here's the final list:

UNIX and bash introduction @maxrjones 
GMT Basics
Symbols and lines - @KristofKoch 
Grids and images - @Esteban82 
Seismology - @maxrjones 
Geodesy - @Xiaohua-Eric-Xu 
Animations - @PaulWessel 

@joa-quim would you be interested in recording GMT basics?

**Comment by joa-quim** [comment]
Sure, I have to do something. That and the GMT.jl

**Comment by maxrjones** [comment]
> Sure, I have to do something. That and the GMT.jl

Great, thanks! And thanks for the reminder about the wrappers. I've added those to the list. What do you and @PaulWessel think about GMT/MEX? Is it worth doing a recording for that too, or should we just focus on GMT.jl and PyGMT?

**Comment by Xiaohua-Eric-Xu** [comment]
Do we want to tag the current short course page (e.g., 2022) and then update it for this year? https://github.com/GenericMappingTools/gmt-for-geodesy

**Comment by KristofKoch** [comment]
I need some guidance from the experienced people here please:

* timeframe of presentation (20min?)
* resolution of video (Full HD -> 1920x1080px?)
* any kind of style template to be used for fonts/logos/appearance?

**Comment by Esteban82** [comment]
The most important thing is the audio. So use any mic as close as possible (instead of the one of the laptop).

**Comment by maxrjones** [comment]
> Do we want to tag the current short course page (e.g., 2022) and then update it for this year? https://github.com/GenericMappingTools/gmt-for-geodesy

Good idea! I will do so tomorrow.

> I need some guidance from the experienced people here please:
> 
>     timeframe of presentation (20min?)

Last year Joaquim covered https://github.com/GenericMappingTools/gmt-for-geodesy/tree/main/3_line_symbols in ~45 minutes. I expect the timeframe for each will be a bit quicker for the recorded videos, given that there shouldn't be any video or audio issues. In general, 20 - 40 minutes for each of the sections seems ideal.


>     resolution of video (Full HD -> 1920x1080px?)

1080p would be great! 720p is the minimum that would work. Agreed that audio is important.

>     any kind of style template to be used for fonts/logos/appearance?

I recommend using one of the bundled themes (classic, modern, or minimal) rather than a custom conf.

**Comment by maxrjones** [comment]
> Hi @maxrjones, it seems that I could not access the Google Drive folder so I just uploaded it to Youtube https://youtu.be/-pJhIfpBkUg.

Thanks! I added your UT Austin email address to the permissions list. I'll need to send the video to Melissa to add to the EarthScope YouTube channel, so it would be easiest for me if you're able to also upload the original to the Google Drive.

**Comment by Xiaohua-Eric-Xu** [comment]
@maxrjones Here's the link to the video https://drive.google.com/file/d/1cxPnf3do0_Ivk8BAuiqeXK_U74eC5PQl/view?usp=share_link. I still could not access the drive though it says that I am a visitor to the directory.

**Comment by Esteban82** [comment]
We need to mark in the survey are the final ones and we want to be available during all of them, or if these are just some options and we will coordinate among ourselves to establish specific hours later?

**Comment by joa-quim** [comment]
Don't spend 2 days in non-stop vacations. You get us worried.

**Comment by maxrjones** [comment]
No worries on the video timing.

@KristofKoch the EarthScope coordinator needs your email and affiliation for the Slack setup. Would send those to me at maxjones@hawaii.edu?

**Comment by Esteban82** [comment]
For the video, which version of GMT should I use, 6.4 or Dev? I would use the Dev version, but I'm afraid it might include some features not included in 6.4.

**Comment by maxrjones** [comment]
> For the video, which version of GMT should I use, 6.4 or Dev? I would use the Dev version, but I'm afraid it might include some features not included in 6.4.

Yes, for that reason GMT 6.4 would be best

**Comment by maxrjones** [comment]
@Esteban82 @joa-quim can you please let me know your timeline for uploading your recordings? Original post with specific lectures is [here](https://github.com/GenericMappingTools/gmt-for-geodesy/issues/33#issuecomment-1560168630) and the folder for uploading is https://drive.google.com/drive/folders/1l_pf1sutmdcHvKl7cvbiJexX5qrniIir?usp=sharing. So far I have Eric and Kristof's and understand that Paul will need a bit more time.

**Comment by joa-quim** [comment]
Hi, I'll need a bit more time too. Thursday probably (but I'll try to have them a bit earlier)

**Comment by PaulWessel** [comment]
@maxrjones, I am starting now.  I am looking at my google slides, but those were done live with breaks where I would switch to the shell and do things live.  How do we replicate that in a single podcast? Do I just record my screen for those sections and narrate, then insert into the slide output.  Not so familiar or happy with Google Slides and thinking of converting to KeyNote...

**Comment by PaulWessel** [comment]
One issue that is specific to animations is if I wish to run animations in zoom (like, playing quicktime).  This went in the toilet when I was working on my Leptouck talk since zoom was extremely slow and the recorded animation jerky.  So I ended up doing it all in keynote whose final output was smooth.

**Comment by Esteban82** [comment]
> @Esteban82 @joa-quim can you please let me know your timeline for uploading your recordings?

Also I need more time. Thursday, but probably tomorrow. I think I will split my video. Probably in 5 (one for each script on [4_Grids](https://github.com/GenericMappingTools/gmt-for-geodesy/tree/main/4_grids)).

**Comment by PaulWessel** [comment]
Splitting into separate sections is a good idea

**Comment by Esteban82** [comment]
Yes, easy to remake it if I don't like.

**Comment by Esteban82** [comment]
I have a doubt. In previous years we make [group excercise](https://github.com/GenericMappingTools/gmt-for-geodesy/blob/main/4_grids/README.md#group-exercise) after each lesson. 

Will we doing that this year? Should I remove/adapt that from the readme file?

**Comment by maxrjones** [comment]
> Will we doing that this year? Should I remove/adapt that from the readme file?

I don't think it will be a group exercise, but would be a great individual one and people can join the office hours to work together if they want.

**Comment by Esteban82** [comment]
Ok, So, I will call it **Final Excercise** and I will say that:

If you have any questions, ask on the Google group chatroom or in the office hours.

**Comment by Esteban82** [comment]
Ok, I will change it back to Slack and add also about the Forum.

**Comment by maxrjones** [comment]
> Ok, I will change it back to Slack and add also about the Forum.

Thanks!

**Comment by joa-quim** [comment]
What backgroud color/patter/image are you guys using for the slides? It wouldn't be bad if we all used a similar look.

**Comment by PaulWessel** [comment]
I am sticking with what I have done the last 5+ years: Plain white google slide with GMT logo in lower left.  See GMT Google folders

**Comment by KristofKoch** [comment]
As it is my first time doing something like this I'd appreciate your feedback on my presentation. Time permitting I could improve it with your input.

**Comment by joa-quim** [comment]
Kristoff I liked a lot. If anything, only a bit long perhaps (or mine is too short 😊)
So that is a PowerPoint animation with narration?

**Comment by PaulWessel** [comment]
I am using zoom - latest M1 version for macOS - and when I select Share screen and pick the Google slide show it gives me a yellow box saying sharing is paused.  Clicking on the large "Resume Sharing" does nothing.  Anyone have any tips?

**Comment by Esteban82** [comment]
Do you mean to record the lessons? I am using OBS Studio.

**Comment by PaulWessel** [comment]
I mean recording my slide talk first.  There has never been a problem with this before.  I got one step further.  I had the Google slides open in a 2nd Safari window (both had lots of tabs), and once I closed the second and opened the slides in the first I was able to share.  So I did a test recording and all looked good until I view the zoom video which is all black with my little head in the top right.  Trying Chrome next...

**Comment by joa-quim** [comment]
This is so annoying. Yesterday I had to repeat 2 or 3 times to make one video because I could never understand when PowerPoint was recording with sound or not. Today I'll be trying OBS for the Julia notebook video.

**Comment by PaulWessel** [comment]
Meanwhile, up north I tried Chrome and that worked. So f***k Safari issue.

**Comment by PaulWessel** [comment]
Now, I am running GMT 6.4 from the bundle since we agreed on 6.4.  Suddenly one of the movie examples run and makes the map but then ends with

```
gmt movie 3_quakes.sh -C360p -T3_times.txt -M50,pdf -N3_quakes -Lc0 --FORMAT_CLOCK_MAP=-
movie [ERROR]: Cannot find file 3_quakes.sh
```

A movie making version ran fine:

`gmt movie 2_earth.sh -C360p -T91 -Fmp4 -N2_earth_360p -Lf -Z`

How can this be? Never seen this before and we hvae made lots of movies.  Same in master.

 gmt --version
6.4.0

**Comment by joa-quim** [comment]
Damn bugbeasts are always waiting for these moments. Had to jump one example in my Julia video because some damn thing decides to screw the CPT under some unknown circumstances.

I uploaded the Julia video but forgot to change the format in OBS to mp4. It is in ``mkv`` that MediaPlayer has no problems in reproducing. Hope the same holds true in YouTube. It looks a nice format. A 20 minutes full screen presentation takes only 143 MB.

**Comment by Esteban82** [comment]
> but forgot to change the format in OBS to mp4. It is in `mkv` that MediaPlayer has no problems in reproducing. Hope the same holds true in YouTube

I am also recording on `mkv` format.

**Comment by joa-quim** [comment]
Well, meanwhile I found a web service that converted it to mp4 and it's now 100 MB.

**Comment by PaulWessel** [comment]
I finally finished my podcast and uploaded it.  However, it was initially a bloated 570 Mb QuickTime output.  After much fussing I used **ffmpg** to grid it down to 80 Mb.  However, now quicktime wont pay it but VNC can.

file says

`Animations.mp4: ISO Media, MP4 Base Media v1 [ISO 14496-12:2003]
`
If anyone knows how to make it playable by Quicktime then please suggest.

Our household is struggling with a cold so I wont be that active the next ays. But slides are up to date, GitHub/7_animatios is up to date and the movie is done but would like macOS people clicking on it to see it.

**Comment by PaulWessel** [comment]
All solved, 66 Mb Animations.mp4 uploaded that plays fine in QuickTIme.  I think I am all set, @maxrjones ?

**Comment by maxrjones** [comment]
> All solved, 66 Mb Animations.mp4 uploaded that plays fine in QuickTIme. I think I am all set, @maxrjones ?

Got it - looks great! Thanks! Hope you all feel better soon

**Comment by Esteban82** [comment]
@maxrjones it seems that I don't have permission to upload the videos to the drive. 
BTW I split my lessons on 5 videos and I recorded them both in Spanish and English, so I will upload 10 videos.

**Comment by maxrjones** [comment]
> @maxrjones it seems that I don't have permission to upload the videos to the drive.
BTW I split my lessons on 5 videos and I recorded them both in Spanish and English, so I will upload 10 videos.

Hmm, I added your gmail address as an editor for https://drive.google.com/drive/folders/1l_pf1sutmdcHvKl7cvbiJexX5qrniIir?usp=drive_link, but let me know if there's a different email address I should add. Otherwise if you want to send me a link to a folder with the videos that would work.

**Comment by Esteban82** [comment]
I have uploaded the files to the drive. I think the audio is a little low but with headphones you can hear them well.

**Comment by maxrjones** [comment]
> I have uploaded the files to the drive on a folder. I think the audio is a little low but with headphones you can hear them well.

Awesome, thanks! I'm uploading all the videos to YouTube now. I equalized the sound to make them a bit easier to hear and merged the video but will add subsections. The title for the video in english is GMT Short Course - Lecture 4 - Grids and Images; can you please share a title to use for the merged video in spanish?

**Comment by Esteban82** [comment]
The title for the Spanish version is: Curso corto de GMT. Clase 4. Grillas e imágenes.

**Comment by maxrjones** [comment]
Thanks everyone for the really excellent work putting together these lectures! Here's the [YouTube playlist](https://www.youtube.com/watch?v=OmtQ1yTWqC4&list=PL3GHXjKa-p6XP5sL0XPdRJhklVNX-N5ht) 🎉 

I've updated the readme and folder order for the 2023 course - please make sure to do a `git pull` on main before making new changes. Let me know if you have problems with merge conflicts.

Here's the office hours schedule again. Zoom and slack info should arrive via email from EarthScope. Looking forward to seeing you all next week!

Who: Kristof, Federico, Joaquim, Max
Topic: GMT Basics, Symbols and lines, Grids and images, Seismology

- Monday June 26 8:30 AM - 10 AM EST - [Time zone converter](https://www.timeanddate.com/worldclock/fixedtime.html?msg=GMT+for+Geodesy+Office+Hours+Part+1+-+GMT+Basics%2C+Symbols+and+lines%2C+Grids+and+images%2C+Seismology&iso=20230626T0830&p1=3918&ah=1&am=30)
- Wednesday June 28 8:30 AM - 10 AM EST - [Time zone converter](https://www.timeanddate.com/worldclock/fixedtime.html?msg=GMT+for+Geodesy+Office+Hours+Part+2+-+GMT+Basics%2C+Symbols+and+lines%2C+Grids+and+images%2C+Seismology&iso=20230628T0830&p1=3918&ah=1&am=30)

Who: Eric, Max
Topic: Geodesy

- Tuesday June 27 9:00 PM - 10:30 PM EST - [Time Zone converter](https://www.timeanddate.com/worldclock/fixedtime.html?msg=GMT+for+Geodesy+Office+Hours+Part+3+-+Geodesy&iso=20230628T21&p1=3918&ah=1&am=30)

**Comment by Esteban82** [comment]
I was watching the install.md file. There are references to old versions of git for windows and python I think (3.9). Is this on purpose? Or the students could use the latest versions?

**Comment by maxrjones** [comment]
> I was watching the install.md file. There are references to old versions of git for windows and python I think (3.9). Is this on purpose? Or the students could use the latest versions?

pygmt supports the latest Python version. I think the latest git would also be fine.

**Comment by KristofKoch** [comment]
Hi everyone, I keep reading "Zoom" but I only got the details for Slack … not sure what is expected from me tomorrow?

**Comment by joa-quim** [comment]
Had that very same doubt today. Than digging in the mails I found a mail from Melissa with the zoom link. Not posting it here because I think it's not a public meeting. Only for those participating in the course. But if you don't find it, please ping me.

**Comment by KristofKoch** [comment]
Thank you for the pointer @joa-quim – found it.

**Comment by KristofKoch** [comment]
Is there an instructors Slack channel?

**Comment by maxrjones** [comment]
I was hoping we'd have a few minutes to talk afterwards today but the zoom room got shut down immediately. I thought that there should be an instructors channel but I don't see it - I'll ask Melissa to create one now so we can discuss any adjustments for Tuesday/Wednesday.
