### ISSUE TITLE
Numbered the folders? 

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt-for-geodesy#6]
Recently I proposed to add a number as a prefix to the folder names (so the folders are order when they are sorted alphabetically. Should I make a PR (and fix some links, I guess)?

I am thinking of using index 0 and 1 digit: 
0_bash
1_basics
2_line_symbols
3_grids
...

**Comment by PaulWessel** [comment]
yes, that is fine by me - just make a PR but watch those internal links in the README and INSTALL files.
